from decimal import Decimal

DATE_FORMAT = "%d/%m/%Y"

CLIENT_MIN_DNI, CLIENT_MAX_DNI = 0, 100_000_000
CLIENT_NAME_CHARS = 30
CLIENT_TEL_CHARS, CLIENT_TEL_OPTIONAL = 15, True
CLIENT_DIR_CHARS, CLIENT_DIR_OPTIONAL = 20, True

ACTIVITY_NAME_CHARS, ACTIVITY_DESCR_CHARS = 20, 100

MAX_CURRENCY = Decimal(1_000_000)

TRANSACTION_TYPE_CHARS = 15
TRANSACTION_METHOD_CHARS = 15
TRANSACTION_RESP_CHARS = 30
TRANSACTION_DESCR_CHARS = 100
